#!/usr/bin/env bun
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";

const scriptDir = dirname(import.meta.url.replace("file://", ""));
const promptPath = join(scriptDir, "../../finetune/system_prompt.txt");
const outPath = join(scriptDir, "../src/generated/system-prompt.ts");

const raw = readFileSync(promptPath, "utf-8");

// Escape backticks and backslashes for template literal
const escaped = raw.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const output = `// AUTO-GENERATED by scripts/bundle-prompt.ts — do not edit manually
export const SYSTEM_PROMPT = \`${escaped}\`;
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, output, "utf-8");

console.log(`✓ Bundled system prompt → src/generated/system-prompt.ts (${raw.length} chars)`);
